#!/bin/bash
set -e

echo "starting databases: $FLEET_CONTROL_DATASOURCE_DB_AUTH, $FLEET_CONTROL_DATASOURCE_DB_VEHICLES, $FLEET_CONTROL_DATASOURCE_DB_DRIVERS, $FLEET_CONTROL_DATASOURCE_DB_ROUTES, $FLEET_CONTROL_DATASOURCE_DB_MAINTENANCE, $FLEET_CONTROL_DATASOURCE_DB_FUEL, $FLEET_CONTROL_DATASOURCE_DB_ALERTS"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_AUTH";
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_VEHICLES";
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_DRIVERS";
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_ROUTES";
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_MAINTENANCE";
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_FUEL";
  CREATE DATABASE "$FLEET_CONTROL_DATASOURCE_DB_ALERTS";
EOSQL